jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "This is a build step"
      - run: echo "kappa"
   
  odc-backend:
    machine: true
    steps:
      - checkout

      - run: chmod +x ./run-depcheck.sh && ./run-depcheck.sh

      - store_artifacts:
          path: reports/dependency-check-report.csv
          destination: depcheck-artifact
  test:
    machine: true
    steps:
      - checkout
      - run: echo "This is a test step"

workflows:
  version: 2
  webgoat:
    jobs:
      - build
      - odc-backend:
        requires: 
          - build
      - test:
          requires:
            - odc-backend
